name: ci
on:
  push:
  pull_request:
jobs:
  build-and-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBS_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build --config Release -j
      - name: Test
        run: ctest --test-dir build --output-on-failure